# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiReader.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 460)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(120, 80, 75, 23))
        self.play.setObjectName("play")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(220, 80, 75, 23))
        self.stop.setObjectName("stop")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 130, 351, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.config = QtWidgets.QPushButton(self.groupBox)
        self.config.setGeometry(QtCore.QRect(240, 140, 75, 23))
        self.config.setObjectName("config")
        self.rate = QtWidgets.QSlider(self.groupBox)
        self.rate.setGeometry(QtCore.QRect(86, 73, 241, 22))
        self.rate.setMinimum(1)
        self.rate.setMaximum(20)
        self.rate.setProperty("value", 10)
        self.rate.setSliderPosition(10)
        self.rate.setOrientation(QtCore.Qt.Horizontal)
        self.rate.setObjectName("rate")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(31, 73, 24, 16))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 40, 300, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.times = QtWidgets.QComboBox(self.layoutWidget)
        self.times.setObjectName("times")
        self.times.addItem("")
        self.times.addItem("")
        self.times.addItem("")
        self.times.addItem("")
        self.times.addItem("")
        self.horizontalLayout_2.addWidget(self.times)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.interval = QtWidgets.QComboBox(self.layoutWidget)
        self.interval.setObjectName("interval")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.interval.addItem("")
        self.horizontalLayout_2.addWidget(self.interval)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 491, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileDir = QtWidgets.QTextEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fileDir.setFont(font)
        self.fileDir.setReadOnly(True)
        self.fileDir.setObjectName("fileDir")
        self.horizontalLayout.addWidget(self.fileDir)
        self.openFile = QtWidgets.QPushButton(self.layoutWidget1)
        self.openFile.setObjectName("openFile")
        self.horizontalLayout.addWidget(self.openFile)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.interval.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "播放"))
        self.stop.setText(_translate("MainWindow", "停止"))
        self.config.setText(_translate("MainWindow", "设定"))
        self.label_2.setText(_translate("MainWindow", "语速"))
        self.label.setText(_translate("MainWindow", "朗读遍数(单行)"))
        self.times.setItemText(0, _translate("MainWindow", "1"))
        self.times.setItemText(1, _translate("MainWindow", "2"))
        self.times.setItemText(2, _translate("MainWindow", "3"))
        self.times.setItemText(3, _translate("MainWindow", "4"))
        self.times.setItemText(4, _translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", "  每遍间隔时长(秒)"))
        self.interval.setCurrentText(_translate("MainWindow", "3"))
        self.interval.setItemText(0, _translate("MainWindow", "1"))
        self.interval.setItemText(1, _translate("MainWindow", "2"))
        self.interval.setItemText(2, _translate("MainWindow", "3"))
        self.interval.setItemText(3, _translate("MainWindow", "4"))
        self.interval.setItemText(4, _translate("MainWindow", "5"))
        self.interval.setItemText(5, _translate("MainWindow", "6"))
        self.interval.setItemText(6, _translate("MainWindow", "7"))
        self.interval.setItemText(7, _translate("MainWindow", "8"))
        self.interval.setItemText(8, _translate("MainWindow", "9"))
        self.interval.setItemText(9, _translate("MainWindow", "10"))
        self.fileDir.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">请选择一个文件</p></body></html>"))
        self.openFile.setText(_translate("MainWindow", "打开文件"))

